### ISSUE TITLE
Move docker/unified_releases to grimoirelab/grimoirelab

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/mordred#30]
Now, we have the `grimoirelab/grimoirelab` for stuff common to all of GrimoireLab. This `unified_releases` file seems like a clear example of that, since it controls which commits in all repos are a part of a release. So, I propose to move the directory to be the `releases` directory in `grimoirelab/grimoirelab`.

If somebody else agrees, I volunteer to produce the corresponding pull requests (here and in `grimoirelab/grimoirelab`).

**Comment by acs** [comment]
Agreed!

**Comment by acs** [comment]
All related to this ticket already done.
