### ISSUE TITLE
[conf] Split conf file in parts

### ISSUE THREAD

**Issue by jgbarah** [grimoirelab/mordred#34]
Most of the configuration file is about the dashboard itself. But a tiny part has to do with the infrastructure needed to produce it: now, that's mainly links to ElasticSearch and MariaDB. I think it would be better to have that part in a separate file. The first one could even be public, so that anyone seeing the dashboard could have access to it. The second one could be private, so that infrastructure details don't get compromised.

**Comment by jgbarah** [comment]
I've uploaded #37 providing an implementation of this.

**Comment by acs** [comment]
#37 merged so closing this ticket!
